# Generated by Django 4.1.13 on 2024-03-14 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anahtar_kelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veriID', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=20000)),
                ('search_keyword', models.CharField(max_length=300, null=True)),
                ('doi_number', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('publication_date', models.DateField()),
                ('anahtar_kelime', models.ManyToManyField(to='main.anahtar_kelime')),
                ('authors', models.ManyToManyField(to='main.authors')),
                ('primarylanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.primarylanguage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
                ('siralama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siralama')),
            ],
        ),
    ]
